############################################
# Network policies
############################################
# Grant ingress communication to httpbin from sleep
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-ingress-from-sleep
  namespace: httpbin-ns
spec:
  podSelector:
    matchLabels:
      app: httpbin
  policyTypes:
  - Ingress      
  ingress:
  - from:
      - namespaceSelector:
          matchLabels:
            name: sleep-ns
        podSelector:
          matchLabels:
            app: sleep
---
# Grant egress communication from sleep to httpbin
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-egress-to-httpbin
  namespace: sleep-ns
spec:
  podSelector:
    matchLabels:
      app: sleep
  policyTypes:
  - Egress
  egress:
  - to:
      - namespaceSelector:
          matchLabels:
            name: httpbin-ns
        podSelector:
          matchLabels:
            app: httpbin